#If you are using a spigot, the plugin supports HEX, e.g. &#000000
#If you are using paper, the plugin supports MiniMessage, such as <#000000>.
#The plugin adapts to your core: paper or spigot.
messages: #Messages
  garbage-command-do-not-have-permission: #If you don't have permission to use command
    enabled: false #Enable or disable message
    message:
      - "You don't have permission" #Message
  garbage-command-open: #Message when player opens trash
    enabled: false #Enable or disable message
    message:
      - "You opened the garbage." #Message

command: #A trash command
  #Permission name will be: trash.command
  trash: #Name of command
    description: "Garbage" #The command description
    usage: "/trash" #The command usage
    aliases: #The command aliases (alternative names)
      - "garbage"

inventories:
  garbage: #Garbage inventory
    size: 27 #Inventory size
    title: "Garbage" #Inventory title
    #Every slot getting from items section.
    #If you need empty slot, enter: "x"
    slots:
      - "YYYYYYYYY"
      - "xxxxxxxxx"
      - "YYYYTYYYY"
    items: #Items section
      Y: #Id of item by unique and use it in slots section.
        type: "decorate" #Type of item, use: "decorate" if you need decoration item
        material: "gray_stained_glass_pane" #Material of item
        amount: 1 #Item amount
        name: "" #Item name
        lore: #Lore of item
         - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
         - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
         - ""
      T: #Id of item by unique and use it in slots section.
        type: "throw" #Type of item, use: "throw" If you need that when a player clicks on an item, they will be taken to the item discard confirmation inventory.
        material: "hopper" #Material of item
        amount: 1 #Item amount
        name: "" #Item name
        lore: #Lore of item
         - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
         - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
         - ""
  confirm: #Confirm inventory
    size: 27 #Inventory size
    title: "<#000000>Confirm" #Inventory title
    #Every slot getting from items section.
    #If you need empty slot, enter: "x"
    slots:
      - "YYYxxxNNN"
      - "YYYxxxNNN"
      - "YYYxxxNNN"
    items: #Items section
      Y: #Id of item by unique and use it in slots section.
        type: "accept" #Type of item, use: "accept" If you need that when a player clicks on an item, it removes the items
        material: "lime_concrete" #Material of item
        amount: 1 #Item amount
        name: "<#000000>Y" #Item name
        lore: #Lore of item
         - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
         - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
         - ""
      N: #Id of item by unique and use it in slots section.
        type: "cancel" #Type of item, use: "cancel" If you need that when a player clicks on an item, it doesn't remove the items
        material: "red_concrete" #Material of item
        amount: 1 #Item amount
        name: "" #Item name
        lore: #Lore of item
         - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
         - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
         - ""