#If you are using a spigot, the plugin supports HEX, e.g. &#000000
#If you are using paper, the plugin supports MiniMessage, such as <#000000>.
#The plugin adapts to your core: paper or spigot.
messages: #Messages
  garbage-manager-help: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "All commands:" #Message
      - " - /garbagemanager create [garbage reload time] - creation a garbage."
      - " - /garbagemanager remove - remove garbage."
      - " - /garbagemanager cancel - undo garbage creation."
  garbage-manager-create-please-click-on-the-block: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "Please click on the block that is supposed to be trash." #Message
  garbage-manager-create-the-block-you-clicked-on-has-a-garbage-status: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "The block you clicked on has a garbage status" #Message
  garbage-manager-create-you-need-to-enter-a-reload-time: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "Usage: /garbagemanager create [reload time]" #Message
  garbage-manager-create-reload-time-you-enter-not-number: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "Reload time you entered is not number." #Message
  garbage-manager-create-you-have-not-finished-creating-the-garbage: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "You haven't finished creating the garbage. Please click on the block that is supposed to be trash." #Message
  garbage-manager-remove-click-on-the-trash: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "Please click on the trash to be deleted." #Message
  garbage-manager-remove-trash-does-not-exist-at-this-location: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "Trash doesn't exist at this location" #Message
  garbage-manager-cancel-there-is-nothing-to-cancel: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "There's nothing to cancel" #Message
  garbage-manager-cancel-successfully: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "You have successfully canceled the current action." #Message
  garbage-manager-remove-successfully: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "The trash has been deleted." #Message
  garbage-manager-create-successfully: #You haven't finished creating the garbage
    enabled: true #Enable or disable message
    message:
      - "New trash has been installed." #Message
  garbage-command-do-not-have-permission: #If you don't have permission to use command
    enabled: true #Enable or disable message
    message:
      - "You don't have permission" #Message
  garbage-command-open: #Message when player opens trash
    enabled: true #Enable or disable message
    message:
      - "You opened the garbage." #Message

command: #A trash command
  #Permission name will be: trash.command
  trash: #Name of command
    description: "Garbage" #The command description
    usage: "/trash" #The command usage
    aliases: #The command aliases (alternative names)
      - "garbage"

inventories:
  trash: #Trash inventory (block)
    size: 54 #Inventory size
    title: "Garbage" #Inventory title
    #Every slot getting from items section.
    #If you need empty slot, enter: "x"
    slots:
      - "YYYYZYYYY"
      - "xxxxxxxxx"
      - "xxxxxxxxx"
      - "xxxxxxxxx"
      - "xxxxxxxxx"
      - "xxxxxxxxx"
    items: #Items section
      Z: #Id of item by unique and use it in slots section.
        type: "decorate" #Type of item, use: "decorate" if you need decoration item
        material: "book" #Material of item
        amount: 1 #Item amount
        #For the name and lore sections only, you can use the time format with %hours%, %minutes%, %seconds%.
        name: "The time before the cleanup: %hours%:%minutes%:%seconds%" #Item name
        lore: #Lore of item
          - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
          - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
          - ""
      Y: #Id of item by unique and use it in slots section.
        type: "decorate" #Type of item, use: "decorate" if you need decoration item
        material: "gray_stained_glass_pane" #Material of item
        amount: 1 #Item amount
        #For the name and lore sections only, you can use the time format with %hours%, %minutes%, %seconds%.
        name: "" #Item name
        lore: #Lore of item
          - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
          - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
          - ""
      T: #Id of item by unique and use it in slots section.
        type: "throw" #Type of item, use: "throw" If you need that when a player clicks on an item, they will be taken to the item discard confirmation inventory.
        material: "hopper" #Material of item
        amount: 1 #Item amount
        #For the name and lore sections only, you can use the time format with %hours%, %minutes%, %seconds%.
        name: "" #Item name
        lore: #Lore of item
          - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
          - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
          - ""
  garbage: #Garbage inventory (command)
    size: 27 #Inventory size
    title: "Garbage" #Inventory title
    #Every slot getting from items section.
    #If you need empty slot, enter: "x"
    slots:
      - "YYYYYYYYY"
      - "xxxxxxxxx"
      - "YYYYTYYYY"
    items: #Items section
      Y: #Id of item by unique and use it in slots section.
        type: "decorate" #Type of item, use: "decorate" if you need decoration item
        material: "gray_stained_glass_pane" #Material of item
        amount: 1 #Item amount
        #For the name and lore sections only, you can use the time format with %hours%, %minutes%, %seconds%.
        name: "" #Item name
        lore: #Lore of item
         - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
         - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
         - ""
      T: #Id of item by unique and use it in slots section.
        type: "throw" #Type of item, use: "throw" If you need that when a player clicks on an item, they will be taken to the item discard confirmation inventory.
        material: "hopper" #Material of item
        amount: 1 #Item amount
        #For the name and lore sections only, you can use the time format with %hours%, %minutes%, %seconds%.
        name: "Throw" #Item name
        lore: #Lore of item
         - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
         - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
         - ""
  confirm: #Confirm inventory
    size: 27 #Inventory size
    title: "Confirm" #Inventory title
    #Every slot getting from items section.
    #If you need empty slot, enter: "x"
    slots:
      - "YYYxxxNNN"
      - "YYYxxxNNN"
      - "YYYxxxNNN"
    items: #Items section
      Y: #Id of item by unique and use it in slots section.
        type: "accept" #Type of item, use: "accept" If you need that when a player clicks on an item, it removes the items
        material: "lime_concrete" #Material of item
        amount: 1 #Item amount
        name: "Yes" #Item name
        #For the name and lore sections only, you can use the time format with %hours%, %minutes%, %seconds%.
        lore: #Lore of item
         - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
         - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
         - ""
      N: #Id of item by unique and use it in slots section.
        type: "cancel" #Type of item, use: "cancel" If you need that when a player clicks on an item, it doesn't remove the items
        material: "red_concrete" #Material of item
        amount: 1 #Item amount
        #For the name and lore sections only, you can use the time format with %hours%, %minutes%, %seconds%.
        name: "No" #Item name
        lore: #Lore of item
         - ""
        enchantments: #Enchantments of item, use: "enchantment:level", example: "unbreaking:1"
         - ""
        itemFlags: #Item flags of item, usage: "ITEMFLAG", example: "HIDE_ATTRIBUTES"
         - ""