name: aGarbage
version: '1.5.2'
main: org.august.garbage.aGarbage
api-version: '1.13'
author: August1251
softdepend:
  - "PlaceholderAPI"
commands:
  garbagemanager:
    description: "The garbage manager."